### ISSUE TITLE
recent-entry.rb errors on FCGI

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-blogkit#17]
Blogkitのrecent-entryプラグインがInsecure operationになるという話が出ている。

http://tdiary-users.osdn.jp/cgi-bin/wforum/wforum.cgi?mode=allread&no=6805&page=0

実装自体はcoreのrecent-listプラグインとほぼ同じなのでそっちでも確認できそうだが、fcgi環境を作れる時間と場所がなくてなかなか試せない。fcgi環境を持ってる人(@hsbtとか?)、誰か手伝って〜。

**Comment by hsbt** [comment]
おっ、RubyKaigi 前なのであれですが時間とれば環境は作れると思います!

**Comment by tdtds** [comment]
助かる！

**Comment by tdtds** [comment]
Blogkit無関係で、fcgiで内部でrequire等をしているプラグインがエラーを起こしてるような感じ。

https://twitter.com/daijin/status/909955874122166272

**Comment by tdtds** [comment]
#18 で直せたと思う。

**Comment by hsbt** [comment]
環境構築まったく手付けられず申し訳なし...
